Description: Criação de bucket no S3
#For more information about properties, access the documentation: 
#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
Resources:

  Brunolimo125: ### Nome do criador do bucket que pode ser chamado como referência depois
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucketcomnomeunico125
      BucketEncryption: ### Criptografia pra o bucket, com SSEAlgorithm padrão da aws
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256